### ISSUE TITLE
Using deprecated Gitlab API v3 instead of v4

### ISSUE THREAD

**Issue by ZsoltKovari** [PavlikPolivka/GitLabProjects#101]
Hi,

I don't use this plug-in at all but as we detected in one of our client's machine, there might be some old Gitlab API usages (v3 namely) coming from this plug-in. Looking at your dependencies, the chance is big that this is the case indeed. Probably you just have to update java-gitlab-api-1.2.5 to a newer version.

The problem about using v3 is that "the old API v3 is going to be removed completely in GitLab 11 this summer". Could you take a look please and update your project accordingly if necessary?

Thank you.

Zsolt

**Comment by PavlikPolivka** [comment]
So I did some experiments with this. 
Not sure if I am doing something wrong but it seems like v3 and v4 apis are not really compatible.

Example
https://gitlab.com/api/v3/projects/3787725/merge_requests/5198368 - works normally
https://gitlab.com/api/v4/projects/3787725/merge_requests/5198368 - gets 404

Are the IDs different between the api versions? 
This requires more time now than I have right now.

**Comment by PavlikPolivka** [comment]
I hope I figured this out.
Changes deployed.
