### ISSUE TITLE
Provided API Token is not valid

### ISSUE THREAD

**Issue by blackeye42** [PavlikPolivka/GitLabProjects#106]
I am trying to connect to gitlab through the plugin.
I get an API token from the Personal Access Tokens page of my gitlab account, selecting all the scopes.
In GitLab Server Url of the plugin settings, I left the default value (https://gitlab.com)
I get a Provided API Token is not valid error.
I have the version 1.6.0

**Comment by lukaszflorczak** [comment]
I have the same problem. When I add token by Php Storm preferences panel there is no error, by then I have always: `Cannot Create Merge Request: Cannot find this project in GitLab Remote` info.

**Comment by PavlikPolivka** [comment]
Hi.
Sorry for your issues. GitLab removed older version of their REST api that were used in this plugin.
I had this reported for a while #101 but I hit some issues with implementation, not it should be released. Can you verify that this was fixed by this? Thanks.

Pavel

**Comment by imekachi** [comment]
I'm currently having the exact same issue with @lukaszflorczak in v1.7.0

**Comment by blackeye42** [comment]
FIxed for me with the 1.7.0 update

**Comment by lukaszflorczak** [comment]
Works great with `v.1.7.0`. Thanks

**Comment by PavlikPolivka** [comment]
@imekachi looks to me more like #105 can you try step suggested there? 
Closing this as it looks like the original issue was fixed.

**Comment by kodytsang** [comment]
uninstall current  GitLab Projects pulgin and try version 1.5.2
