### ISSUE TITLE
Allow Issues to be created in the IDE

### ISSUE THREAD

**Issue by Duke02** [PavlikPolivka/GitLabProjects#107]
If we can already do Merge Requests, why can't we create Issues? It seems like it could be a really nice feature and allow us to do more work from within the IDE.
I only say this because some workflows for software development create issues, then make a branch to address that issue, then merge and repeat.

**Comment by PavlikPolivka** [comment]
To be honest I am doing developing this plugin to fit needs of workflow we
do in the place where I work, we do not use gitlab comments so I do not
have the need to add support. I can have it on my todo list of stuff to add
but it will not be very high.

Pavel

**Comment by Duke02** [comment]
Ok thank you for putting it on the list.

**Comment by PavlikPolivka** [comment]
I just remembered that intellij already has in IDE support for issues. If I remember correctly it has gitlab support out of the box...

https://www.jetbrains.com/help/idea/managing-tasks-and-context.html
