### ISSUE TITLE
Unable to update in Android Studio.

### ISSUE THREAD

**Issue by vasili200apps** [PavlikPolivka/GitLabProjects#110]
Hello, whenever I try to update the Plugin in Android Studio the most updated version offered is 1.5.3 

I saw in this page https://plugins.jetbrains.com/plugin/7975-gitlab-projects that the most recent version is 1.7.0 but I can't seem to access it from the  IDE default plugin installer. do I need to add some other repository? I am using Android Studio version 3.1.3

**Comment by PavlikPolivka** [comment]
Plugin is provided only for latest versions of ides. I am not familiar with
Android studio but you may need to update.
