### ISSUE TITLE
API v4

### ISSUE THREAD

**Issue by nkuehnel** [PavlikPolivka/GitLabProjects#112]
When I want to import an existing IntelliJ project to gitlab using my personal access token, I get a FileNotFoundException: https://gitlab.xxx.de/api/v3/namespaces?private_token=xyzxyzxyz

When I type this into my browser I get the following hint:
{"error":"API V3 is no longer supported. Use API V4 instead."}

Is it possible to change this address in the plugin using v4 instead of v3?

Thanks!

**Comment by PavlikPolivka** [comment]
Hi. It's fixed in latest verison of the plugin (few months now), please upgrade.
