### ISSUE TITLE
Authentication failure - cloning projects asks for password, even when token from pycharm is added

### ISSUE THREAD

**Issue by sidx64** [PavlikPolivka/GitLabProjects#114]
Authentication failure - cloning projects asks for password, even when personal access token from pycharm is added

1. Recently completely re-installed Pycharm 2018.2
2. I went to my gitlab-ce self hosted app and in my settings, created a key for pycharm to use.
3. I went to Preferences > GitLab Settings and provided the server name and GitLab personal access token
4. Opened PyCharm and selected Checkout from Version Control > Git. A set of my projects showed up in the dropdown. I chose one to clone.
5. Clicked on Test or Clone buttons. Both result in asking for username and password. Entering correct credentials does not work either. The login and password window reappear.

I am not sure if this is a bug, or there's something I am doing wrong. Please help.

**Comment by sidx64** [comment]
If I try to cancel on the login window, I get the error: "Repository test Failed" or "Repository Clone Failed" with Authentication failure.

**Comment by sidx64** [comment]
Update:

This seems to be happening only with the latest version of Gitlab CE - 11.2 
We reverted back to 11.1.4 and everything is back where it belongs. 

I believe there are issues with the plugin and the latest version of Gitlab.

**Comment by PavlikPolivka** [comment]
Hi. This plugin does not do anything about checkout. Checkout is done by
IDE. If you are having problems during checkout you need to solve it with
JetBrains.

Pavel

**Comment by sidx64** [comment]
Hi Pavlik!

Firstly, thank you for creating this plugin. It is immensely helpful. 

If the plugin has nothing to do with check-outs, clones, commits or remote push, I guess the issue is with GitLab itself. I am closing this issue and raising a new one with GitLab
