### ISSUE TITLE
Wrong username/password for clone while pull and push works correctly

### ISSUE THREAD

**Issue by pagodzik** [PavlikPolivka/GitLabProjects#115]
I use GitLab since many months. All works good.
Now I wish to clone other repository (oter project) from the same GitLab account. I can't - there is "username/password invalid" warning.
How can I add correct username and password?

**Comment by PavlikPolivka** [comment]
Hi.
The actual checkout if done by IDE and your git installation so you need to change your username and password there. Plugin only provides urls to repos, rest is done by normal git checkout in your IDE. There is no option to add usernames to the plugin.

**Comment by pagodzik** [comment]
I understand, so why there is no problem with push and pull, but there is impossible to make git clone? My coworker do the same things and he make clone without problem.
