### ISSUE TITLE
maybe not supported API version support

### ISSUE THREAD

**Issue by devatlant** [PavlikPolivka/GitLabProjects#116]
Plugin version 1.7.0
Idea version - 2018.1

My gitlab version - 8.13.0

In the gitlabs logs I see this message:
`  Parameters: {"private_token"=>"[FILTERED]", "unmatched_route"=>"api/v4/user"}`

**Comment by devatlant** [comment]
> When to expect support protocol GitLab API version 4

I guess the version 4 is actually supported

My problem is linked to too old GitLab API which is not any more compatible with latest plugin version. Can anyone list the exact supported versions of GitLab API?

**Comment by PavlikPolivka** [comment]
Hi I am testing this plugin against latest version of GitLab, not sure in what version they deprecated old API calls.

It's not in my power to maintain multiple versions with legacy support.

**Comment by PavlikPolivka** [comment]
Here is a gitlab page about this change.

https://about.gitlab.com/2018/06/01/api-v3-removal-impending/

So I guess that plugin only supports GitLab 11 released June 22, 2018 and higher.

**Comment by devatlant** [comment]
Is it possible to use an older version of this plugin which is compatible with v3?

**Comment by PavlikPolivka** [comment]
It should be.

Here you can download older versions.
https://plugins.jetbrains.com/plugin/7975-gitlab-projects

You need to install the jar file manually tho.
