### ISSUE TITLE
Provided API Token is not valid

### ISSUE THREAD

**Issue by SyDroX** [PavlikPolivka/GitLabProjects#121]
Greetings, 

I'm trying to setup my gitlab project to work with webstorm and I am getting this error:
![image](https://user-images.githubusercontent.com/12381844/48062029-76a4fb80-e1c9-11e8-85b2-21112d2452e5.png)

I created an access token with api read/write access to the API.

**Comment by PavlikPolivka** [comment]
Hi.

Your gitalui url is wrong. Just follow the example and put in
https://gitlab.com/ not full url of the repository.

Any suggestions how to make this less confusing? I thought that the example
is clear enough, but people keep doing it wrong.

Pavel

**Comment by SyDroX** [comment]
Hi,
Thanks for the quick answer!
About the confusion, correct me if I'm wrong I'm not an expert on vcs or gitlab.
However, I don't see why you need 2 fields there. Maybe change it to look like this?
![image](https://user-images.githubusercontent.com/12381844/48134024-59dbf700-e2a1-11e8-9b5e-13f66229c155.png)

Or perhaps turn the first field into a dropdown select without a free text option.

**Comment by PavlikPolivka** [comment]
You do not needto fill the repository URL at most of the cases. That is there for special GitLab installs where UI runs on one URL but checkout is from different one. It's quite rare and bit confusing, my plan is to add the second field to some advanced setting popup where I could have more text explaining it.

**Comment by SyDroX** [comment]
Yeah that could work as well.

**Comment by LennartSteinbacher** [comment]
Dear all, I have a similar issue. I just type in the server URL and get directed to the correct token page, where I have created a token with API Access scope. Now I am confused because I get the error message "Provided API Token is not valid". I tried the Name of the token as well as the "mixed-up-letter"-token from the feed token area below… both is not valid. I'm using GitLab Projects 2.0.1 and pycharm 2018.2.4 community Edition.
I'm thankful for any help!

**Comment by liuyt-15** [comment]
> Dear all, I have a similar issue. I just type in the server URL and get directed to the correct token page, where I have created a token with API Access scope. Now I am confused because I get the error message "Provided API Token is not valid". I tried the Name of the token as well as the "mixed-up-letter"-token from the feed token area below… both is not valid. I'm using GitLab Projects 2.0.1 and pycharm 2018.2.4 community Edition.
> I'm thankful for any help!

I use GitLab Projects 2.0.1 and IDEA 2018.1.  File ->new -> project from version control. You can directly clone a project from remote.

**Comment by groovyman** [comment]
The problem is still there, when you use a local installation of a github
similar to this https://fhr.xxx-xxxxon.de:6443

**Comment by krisavi** [comment]
Seems to be the issue of 2018.1 Having it on PyCharm and IntelliJ. But not on IntelliJ Educational which is a lot newer version.

**Comment by AlekseiMarinichenko** [comment]
![Screenshot_20200224_132228](https://user-images.githubusercontent.com/25913340/75148654-d7cb4800-5708-11ea-9481-649eb0b8fb8b.png)
Filling the field with https://gitlab.com/ gives an error.

**Comment by dubu2** [comment]
Seriously JetBrains, how have you not fixed this yet?

**Comment by Haagimus** [comment]
Has anyone discovered a solution to this yet, or is the plugin still broken?

**Comment by kchvilyov** [comment]
Has anyone discovered a solution to this yet, or is the plugin still broken?

**Comment by simon-liebehenschel** [comment]
Plugin is not required. Also, it is deprecated, so I would not wait for any fixes or updates.


### To work with GitLab:

Clone GitLab project:
```bash
https://**GitLabUserName**:**YOUR_WRITE_REPOSITORY_TOKEN**@gitlab.com/your_project_path.git
```

For Pull, Push, etc. use PyCharm built-in options.

**Comment by skofkidosif** [comment]
Need to write right Expiration date. It was good for me

**Comment by skofkidosif** [comment]
more time after current date
