### ISSUE TITLE
No gitlab menu in settings->version control

### ISSUE THREAD

**Issue by smartrahat** [PavlikPolivka/GitLabProjects#125]
I have some issues Integrating GitLab with PhpStorm.

1. There is no gitlab menu in _File -> Settings -> Version Control_
2. Nothing happen when I click _VCS -> Import into version control -> Share on Gitlab_
3. An error message is showing when I click _VCS -> Checkout from Version Control -> GitLab_. The error says. **"No Gitlub Servers. No Gitlab Server are configured. Please add servers in settings."**

I have restarted PhpStorm several times, but it's not working.

**Comment by PavlikPolivka** [comment]
This is location of the settings.
![image](https://user-images.githubusercontent.com/7499182/53120506-4c960000-3552-11e9-8a9a-bb882f982bfa.png)
This location is only in the most recent version of the plugin. Previously it was in Other Settings.
