### ISSUE TITLE
Cannot create merge request 

### ISSUE THREAD

**Issue by shmaram** [PavlikPolivka/GitLabProjects#127]
Hello

I just installed the pulgin and I get an error "cannot create merge request - Cannot find this project is GitLab remote" .
![image](https://user-images.githubusercontent.com/12017112/49162048-c1caae00-f332-11e8-8cbe-52ac95f5370d.png)

I would like to say that I am able to pull, push and fetch from the remove. 

My config is :
![image](https://user-images.githubusercontent.com/12017112/49161999-ac558400-f332-11e8-893d-eab5d90950e7.png)

Thanks 
Shahar

**Comment by eamigo86** [comment]
Hi @shmaram, any progress?

**Comment by PavlikPolivka** [comment]
Leave the repository URL field empty ...
Or put in the the correct format (as in example).

This is used only if you are doing checkouts from different url than the UI and REST API runs. 
If the repository url and UI is the same you leave it empty, us just do the domain name, not fully quilified URL. 

Any ideas how to make this more clear as clearly the example, and the live that is trying to say to leave it blank does not work??
