### ISSUE TITLE
Make sharing menu item name consistent with existing for GitHub

### ISSUE THREAD

**Issue by pbaranski** [PavlikPolivka/GitLabProjects#129]
https://github.com/PavlikPolivka/GitLabProjects/blob/54f9008f6cbcbf997e4fb160c7eff7435648e6a9/src/main/java/com/ppolivka/gitlabprojects/share/GitLabShareAction.java#L54
In menu VCS->Import into Version Control
I suggesting renaming option name form `Share on GitLab` to `Share Project on GitLab` to make it consistent with `Share Project on GitHub` build in option.

**Comment by PavlikPolivka** [comment]
Done.
