### ISSUE TITLE
Asks for login on clone when using Access Token

### ISSUE THREAD

**Issue by snebjorn** [PavlikPolivka/GitLabProjects#134]
I'm getting a login prompt that fails even though I set an Access Token. I'm using 2FA so the login obviously doesn't work.

The self hosted GitLab server I'm connecting to is running `GitLab Community Edition 11.5.3`. 

GitLab Projects version is `2.0.0`.

My IntelliJ version

> IntelliJ IDEA 2018.3.1 (Community Edition)
> Build #IC-183.4588.61, built on December 4, 2018
> JRE: 1.8.0_152-release-1343-b16 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

Here's my setup:
![image](https://user-images.githubusercontent.com/1266245/50161848-26977980-02dd-11e9-8ff6-ae4b0031a443.png)

I can choose what repos to clone from the GitLab remote, so I do have access
![image](https://user-images.githubusercontent.com/1266245/50161954-652d3400-02dd-11e9-9847-5381b492995f.png)

However when I clone the project this pops up and fails with what ever I put in there. After 3 attempts it fails with saying that I need to setup an Access Token. Which I already did.
![image](https://user-images.githubusercontent.com/1266245/50161997-7f671200-02dd-11e9-883c-22fc8bdd9ef3.png)

Please advise.

**Comment by PavlikPolivka** [comment]
Access token is used only for gilablab API actions ... git checkout is normal git action done by your git installation and you still need to authenticate.
