### ISSUE TITLE
Adding a new Gitlab Server overwrites existing Server values 

### ISSUE THREAD

**Issue by access3000** [PavlikPolivka/GitLabProjects#136]
My Environment:

PhpStorm 2018.3.3
Build #PS-183.5153.36, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

I have 2 Projects. I added a successfully an Gitlab Server for one project. I have both projects  openend simultaneously. If i add a new Gitlab Server  for the second project, the data for the first Gitlab Server is overwritten and no second entry is added.

**Comment by PavlikPolivka** [comment]
You can only add one server url once. 
It does not make more sense to add it twice..
