### ISSUE TITLE
Cannot configure API key

### ISSUE THREAD

**Issue by famoser** [PavlikPolivka/GitLabProjects#24]
I cannot configure the API key, as the field in the SettingsDialog is not visible.
I'm pretty sure this worked in previous versions (as this plugin is working very well on another machine).

Is there a workaround so I can configure the API key myself?

**Comment by PavlikPolivka** [comment]
Hi,
I look fine in IntelliJ IDEA 2016.1.1 for me. Can I see screenshot?

There are couple ways of configuring it.
- VCS -> Checkout from version control -> GitLab -> Configure button
- File -> Settings -> Other Settings -> GitLab Settings
- You can create plugin settings file manually
-- Go to
--- Windows: <SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.<PRODUCT><VERSION>
--- OS X: ~/Library/Preferences/<PRODUCT><VERSION>
--- Linux: ~/.<PRODUCT><VERSION>
-- cd config/options
-- There should be gitlab-project-settings.xml - edit that
-- if there is not you can use the one attached to this comment


I will look into this as soon as possible.
[gitlab-project-settings.zip](https://github.com/PavlikPolivka/GitLabProjects/files/206268/gitlab-project-settings.zip)

**Comment by famoser** [comment]
I have the same problem in both phpstorm and intellij. Screenshots appended:
![intellijscreenshot](https://cloud.githubusercontent.com/assets/5077020/14314932/ad84c3fe-fbfa-11e5-9837-b50134c604d3.png)
![intellijversion](https://cloud.githubusercontent.com/assets/5077020/14314934/ada46420-fbfa-11e5-834a-9e82fecfd870.png)
![phpstormversion](https://cloud.githubusercontent.com/assets/5077020/14314935/ada4a782-fbfa-11e5-894f-2f5f87ffca73.png)
![phpstormscreenshot](https://cloud.githubusercontent.com/assets/5077020/14314933/ada3b610-fbfa-11e5-9187-aa92053b2c72.png)
I have managed to configure the API key using File -> Settings -> Other Settings -> GitLab Settings,
thanks for your fast response!

**Comment by PavlikPolivka** [comment]
These look huge. Are you using some kind of upscaling (for high-res monitors)? Size of those dialogs is done in pixels, so I guess it might work wrong with some upscaling? 

What OS and resolution and system upscaling (if any) are you using? 
I will try to figure out how to scaleable dialogs and release fix for this as soon as possible.

**Comment by famoser** [comment]
You were right, it is a problem with the upscaling. I've taken some screenshots:
<img width="290" alt="150 2560" src="https://cloud.githubusercontent.com/assets/5077020/14329484/cfaf8126-fc3b-11e5-999e-455bdcfbc863.png">
150%, 2560 wide
![175 2560](https://cloud.githubusercontent.com/assets/5077020/14329485/cfb11676-fc3b-11e5-9fb1-83990040eb06.png)
175%, 2560 wide
![125 1920](https://cloud.githubusercontent.com/assets/5077020/14329487/cfb96c9a-fc3b-11e5-8ce4-c12428ee58f9.png)
125%, 1920 wide
![125 2560](https://cloud.githubusercontent.com/assets/5077020/14329486/cfb9593a-fc3b-11e5-9896-bd9715cdd401.png)
125%, 2560 wide

Resolution seems to be irrelevant, only the upscaling has an impact.
I'm using Windows 10, I've changed the upscaling under System -> Display. I've had to relog for changes to take effect.

**Comment by PavlikPolivka** [comment]
I released new version without pixel sizes on dialogs. Some dialogs seemed broken so I tried to do little bit of vertical scaling. Hopefully this will look OK, I am on Windows 7 now and I cannot try it on 10. It looked fine on Win7 on 14 inch fullHD display without any scaling.

I will try it on win10 next week and try to fine tune it for all scaling cases.

**Comment by famoser** [comment]
![200 2056](https://cloud.githubusercontent.com/assets/5077020/14343555/21127288-fca2-11e5-8319-49ea5f6dab68.png)
200%, 2560 wide
It works now as expected, thank you very much. I even increased the scaling further to 200%, and still both fields are visible. Also I can now resize the window, I'm not sure this has worked before.
Thanks for your work!
