### ISSUE TITLE
Unable To Push On Windows

### ISSUE THREAD

**Issue by barrycarey** [PavlikPolivka/GitLabProjects#25]
Unable to push to repo on Windows. 

From log: 

#git4idea.commands.GitHandler - git -c core.quotepath=false push --progress --porcelain test10 refs/heads/master:master 
#git4idea.commands.GitHandler - sh: 1: git-receive-pack: not found 
#git4idea.commands.GitHandler - fatal: Could not read from remote repository. 
#git4idea.commands.GitHandler - Please make sure you have the correct access rights 
#git4idea.commands.GitHandler - and the repository exists. 

I also receive this error when pushing directly via the commandline.  However, setting %home% to %userprofile% fixes it. 

I'm unsure if this issue is related to WebStorm or the plugin.

**Comment by PavlikPolivka** [comment]
Hi, 
This looks like issue with your git settings on Windows. Intellij (webstorm) uses command line for git operations, so if you have to do some special setting for command line to work IDE is not doing that. 
This plugin is calling IDE apis for all git operations, so if git is not working properly in IDE and command line it will not work in plugin. 


That log you attached is from git4idea (git plugin for all JetBrains IDEs) and is saying that target repo cannot be found or authenticate you. 
Are you using ssh or http checkout? It looks to me that you have problems with authentication to remote.

**Comment by barrycarey** [comment]
That's alone the lines of what I was thinking. 

It does appear to be a config issue somewhere on my side.  Works fine on my Linux laptop, just my Windows desktop with the issue. This is my first time using something besides Github with WebStorm. 

I can push from the Windows CL normally.  However, when doing it from the terminal in WebStorm I get fatal: protocol error: bad line length character: git@

At a guess it's not able to grab my SSH key. 

Since this is not related to your plugin you can feel free to close the issue.
