### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by mbbush** [PavlikPolivka/GitLabProjects#26]
Would it be possible to support viewing and/or posting comments to open merge requests? I find that IntelliJ's diff tool is much easier to use than gitlab's (for instance, it has better support for hiding whitespace changes, or large diffs), but the inability to create comments from within IDEA is limiting.

**Comment by PavlikPolivka** [comment]
Hi. Yes it's possible. Another plus would be that you could see results of your builds on this merge request (those are comments as well). I will have some time during this weekend, I will try to do something with comments.

**Comment by mayboroda** [comment]
Any luck on having this enhancement to be implemented?

**Comment by PavlikPolivka** [comment]
Sorry I was extremely busy. I will look into this this or next weekend,

**Comment by PavlikPolivka** [comment]
I have added basic support for comments on merge requests. 
There is new Comments button under Diff button. 
It will display list of comments on issue. Double click on comment will display comment details.
User also can add comments with Add Comment button.

Please check it out. If you have some ideas for enhancements please create new issue, closing this one.

**Comment by mayboroda** [comment]
Thanks, I'll check and make a feedback. Thanks.
