### ISSUE TITLE
Can't get a list of merge request after update

### ISSUE THREAD

**Issue by mayboroda** [PavlikPolivka/GitLabProjects#30]
Gitlab version:
```
GitLab 7.14.3

GitLab Shell 2.6.5

GitLab API v3

Ruby 2.1.6p336

Rails 4.1.11
```

Plugin version:
`1.3.2`

Plugin configurations:
`gitlab url: https://gitlab.paycash.eu`
gitlab token is also there

On `get list of merge requests` I'm getting pop-up with `Cant't create merge request. Can't find GitHub remote` and in the Event logs
```
13:28:08 Cannot Create Merge Request: Can't find GitHub remote
13:28:08 IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog. must not be null (show balloon)
```

**Comment by PavlikPolivka** [comment]
I will look into this as soon as possible.

**Comment by PavlikPolivka** [comment]
Sorry for late reaction.

Looks like plugin cannot find gitlab (it says github for some reason) remote.
If you do git remote -v what is url of you gitlab remote?

If it's http and you have https in plugin settings it will probably fail. I need to fix this.

**Comment by PavlikPolivka** [comment]
I did better remote check, it works now for all my test GitLabs, but not sure if it helps you. Can you try a tell me if it works for you now? If not please post here output of git remote -v on your project directory.
