### ISSUE TITLE
bug: Cannot Create Merge Request: Can't find GitHub remote

### ISSUE THREAD

**Issue by mkovel** [PavlikPolivka/GitLabProjects#32]
Cannot Create Merge Request: Can't find GitHub remote
IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog. must not be null (show balloon)

PhpStorm 2016.1.2
Build #PS-145.1616, built on May 24, 2016
JRE: 1.8.0_77-b03 x86

**Comment by mkovel** [comment]
It happend when i try use List Merge Requests

**Comment by PavlikPolivka** [comment]
This duplicates #30 Closing
