### ISSUE TITLE
Add support for selecting assignee at new merge request

### ISSUE THREAD

**Issue by disharmonized** [PavlikPolivka/GitLabProjects#36]

**Comment by umitk** [comment]
Hi, We need this feature too and we are waiting for this. What is your plan to release this?

**Comment by PavlikPolivka** [comment]
Hi, I am working on it. 
I managed to search users via GitLab API and now I need to create UI for this. 

My plan is to release this sometime next week.

**Comment by PavlikPolivka** [comment]
Ready for release in version 1.4.0
