### ISSUE TITLE
Merge request in multi-module project

### ISSUE THREAD

**Issue by JChrist** [PavlikPolivka/GitLabProjects#37]
There seems to be an issue currently with the plugin when trying to create a merge request for one module inside a multi-module project, with each module on a different gitlab repository. 
The merge request is created at the wrong project, I tend to believe it uses the first module it finds with a gitlab repo.
I think this could either be addressed by finding the "active" module (e.g. current file being displayed in the editor), or by adding option to select it in the dialog.

**Comment by PavlikPolivka** [comment]
Not sure what you mean by multi module project?

Right now there can only be one gitllab repository in one project for merge requests to work.
I suppose there could be combo box listing all gitlab repos on the merge request screen.

**Comment by PavlikPolivka** [comment]
This was fixed by using the project from active file.
