### ISSUE TITLE
GitLab integration Bug (URL's wrong)

### ISSUE THREAD

**Issue by xstable** [PavlikPolivka/GitLabProjects#45]
Postet it here: https://youtrack.jetbrains.com/issue/WI-33885

**Long term:** 

**What steps will reproduce the problem?**
1. Go to VCS ⇒ Import into Version Controll ⇒ Share on Gitlab
2. Fields are pre-filled with Server-URL and GitLab API Key (or fill in your's) [my URL Scheme is: https://gitlab.com/xstable]
3. Press the Questionmark beside API-Key Field

**What is the expected result?**
Profile-Page on Gitlab should open

**What happens instead?**
404 Error-Page opens with this schema: https://gitlab.com/xstable/profile/account
But the Profile-Page is now: https://gitlab.com/xstable or: https://gitlab.com/profile [seems to get the user by session after login]

**Please provide any additional information below**
Anyway, if I click on OK, instead of the questionmmark, I get to an Dialoge where I could setup the Projekt (set Name, access (public, private, internal), Auth-Type, and Message.
If I press the refresh-Button to get all groups from Server, it won't work. I think this is also cause of the URL-Bug.

Currently, GitLab-Share in this way dosn't work at all. Please Fix it.
![auswahl_065](https://cloud.githubusercontent.com/assets/1778068/20176774/a59c553a-a749-11e6-93b0-f50e392e8f23.jpg)

**Comment by xstable** [comment]
Still same Bug after Update today to 2016.3

**Comment by PavlikPolivka** [comment]
Hi. Sorry for late response. 
You are using wrong url for the gitlab server. use only https://gitlab.com/

![image](https://cloud.githubusercontent.com/assets/7499182/21565301/72ec3ffa-ce96-11e6-8298-b5e6ed755d55.png)
