### ISSUE TITLE
Identified Issue that can cause "Cannot Create Merge Request: Cannot find this project in GitLab Remote"

### ISSUE THREAD

**Issue by Kieranphs** [PavlikPolivka/GitLabProjects#47]
I ran in to this error and with some effort was able to find that the cause of it for me was that int he .git folder config file the url did not have the .git on the end of the string.

**Comment by PavlikPolivka** [comment]
Thanks. This helped a lot. Closing this issue.

**Comment by annrayc** [comment]
I still don't understand what needs to be changed here and in which .git are we talking about.
what is the solution to this ?

![](https://files.slack.com/files-pri/T095ZJLPK-F5AQLTAAH/screen_shot_2017-05-09_at_9.46.41_pm.png)
