### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by natros** [PavlikPolivka/GitLabProjects#5]
I think the background of "Listing GitLab Projects" should be white with the default theme. 

Please add a button to check out the project.

IntelliJ IDEA (Minerva) IU-143.379.11
Build #IU-143.379, built on October 20, 2015
JRE: 1.8.0_66-b17 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

OSX 10.11.1

![listing_gitlab_projects](https://cloud.githubusercontent.com/assets/4996289/10715539/b8fd2362-7b11-11e5-9adc-d690f7549d5a.png)

**Comment by PavlikPolivka** [comment]
Fixed in 1.0.1
https://github.com/PavlikPolivka/GitLabProjects/pull/7

Still doing some testing with one issue in this milestone, release is planned sometime this week.
