### ISSUE TITLE
Allow default checking of 'Remove Source Branch (After Merge)'

### ISSUE THREAD

**Issue by Mbuckley0** [PavlikPolivka/GitLabProjects#52]
* I think it would be good to have an option to have the 'Remove Source Branch (After Merge)' option checked by default

**Comment by PavlikPolivka** [comment]
Hello. 

How this should work? 
There is few options for this. 
- it can remember last selected value (can be confusing but no additional settings needed) 
- add default value setting for this to the plugin settings (more work to do, right now only universal settings are there and this would be specific settings for one functionality) 
- have it checked by default without any settings (easy to do and I am not opposed to it, right now when you create mr in gitlab it's not checked, this would be inconsistency) 

I am not opposed to this but I am not sure what is best option for this.


Pavel

**Comment by Mbuckley0** [comment]
Sorry for the delay in response. I think the best option there is to remember the last selected value and use that at least for the time being.
