### ISSUE TITLE
Android Studio hangs when entering ":" char in the "GitLab Server Url" box

### ISSUE THREAD

**Issue by pavlus** [PavlikPolivka/GitLabProjects#67]
Fresh new installation of Android Studio 2.3.3, trying to import first project from VCS, selecting GitLab, entering API token, entering  server URL, everything works just fine until i add ":" character to it, I can type URL without it and then add and it still hangs.

UPDATE:
It's not actually Studio that hangs, it's settings dialog, and it works after some time, about minute, but for that minute dialog is frozen, no animations, editing not possible.

Probably it's not caused by ':' character, but well-formed looking address.

**Comment by PavlikPolivka** [comment]
The dialog is doing validation with each character changed. 
Unfortunately when you type the : and a number it's most probbly not the correct url until you write at lease one more number.

Example https://gitlab.com:8 
The library for api validation I am using has connection timeout one minute.
That is bad.
I am changing the timeout on my end to be just half a minute.
