### ISSUE TITLE
Can't find  GitLab remote

### ISSUE THREAD

**Issue by paydaycay** [PavlikPolivka/GitLabProjects#71]
Hi, 

I'm trying to use this plugin. 
Unfortunatly, I can't use it because my server url is quite different than my remote url.

Here is an example : 
- setting url : https://git-web.example.com/
- remote url : git@git.example.com:group/project.git

I also tried to use https for remote url instead of ssh but I got the same issue.

**Comment by Horoneru** [comment]
Have you tried editing the remote to be git.example.com:group/project.git ?
In my case, it worked.

It seems remotes with the username do not work (username@HOST/group/project.git doesn't work while HOST/group/project.git works)

The fix may be trivial though, I'll be looking into it in my free time

**Comment by PavlikPolivka** [comment]
Hi all,
It should work with the user name. I am using it that way. 

Problem here is with two different domains is settings 

git-web.example.com
and on remote 
git.example.com

Those two must match for plugin to figure that remote is the gitlab remote. If those two do not match for some reason (seems strange, but you know ....) it will not work. 
If this is actual use case that somebody needs (not sure why) it would be possible to add another field to config dialog that would allow you say what your other domain is.
I am not implementing this util I get verified that this is a usecase :D

**Comment by PavlikPolivka** [comment]
So my suggested fix for this a additional field on the setting dialog.
The field would be named something like gitlab repo domain (it would be a string that the plugin will look for in the git repo to verify that that is the correct gitlab repo) this field would be prefilled from the normal gitlab url field but could also be overridden and set to whatever.

This would correct this problem and does not seem that hard to do.

**Comment by robstoll** [comment]
In my case the problem was also the username in the .git/config file, once I removed it it worked
