### ISSUE TITLE
Add [WIP] to Merge Request Name to Title

### ISSUE THREAD

**Issue by kaiszy** [PavlikPolivka/GitLabProjects#72]
Hi,

we use gitlab for our deployment (merge requests). The release manager checks all Merge Requests without [WIP] Tag in Title. Is it possible to add this in the title (configurable) ? In the moment the "merge requester" have to do it by hand (and some developers forget it...).

Best regards,
  Kai.

**Comment by PavlikPolivka** [comment]
Hi, so there would be additional checkbox to mark it as Work in Progress? 

I can do that. Not sure when but this should not be that hard to do.

**Comment by PavlikPolivka** [comment]
OK, This was not that hard :D I added the checkbox and released new version. 
Hope this helps you,
