### ISSUE TITLE
Remove Source Branch (After Merge) doesn't work

### ISSUE THREAD

**Issue by rippi** [PavlikPolivka/GitLabProjects#78]
The checkbox "Remove Source Branch (After Merge)" doesn't work with GitLab Community Edition 8.12.10.
The created Merge Request isn't marked to be deleted after merge.

**Comment by PavlikPolivka** [comment]
Works with the newest one (not sure what our current version is). 
This maybe that the 8.12.10 does not support this via REST API.
Closing this as I cannot reproduce this and I will not support older versions.
