### ISSUE TITLE
Java exception in PhpStorm 7.1.3

### ISSUE THREAD

**Issue by alarcia** [PavlikPolivka/GitLabProjects#81]
Hello, thanks for your awesome job!

When I install GitLabProjects on PhpStorm 7.1.3, and open VCS menu, and hover over "Import into version control" ("Checkout from version control" is just gone, I guess it is related), the event log throws this:
PluginException: cannot create class "com.ppolivka.gitlabprojects.merge.request.GitLabMergeRequestAction" [Plugin: com.ppolivka.gitlabprojects]: cannot create class "com.ppolivka.gitlabprojects.merge.request.GitLabMergeRequestAction" [Plugin: com.ppolivka.gitlabprojects]

Also VCS -> Git -> GitLab is greyed out.

Earlier this afternoon, the exception from [this issue](https://github.com/PavlikPolivka/GitLabProjects/issues/27) was also thrown (I was not able to fix it though). But it is happening no more. Maybe somehow is related.

Thank you and have a nice day! :)

**Comment by PavlikPolivka** [comment]
Hi.

This means your PhpStorm runs on Java 7 or lower. 
Plugin is written in Java 8.

Please upgrade to newer version o force it to run on newer Java (8 or above).

I do not have time to support older Java versions.
