### ISSUE TITLE
Multiple GitLab Servers

### ISSUE THREAD

**Issue by JSosaRDZ** [PavlikPolivka/GitLabProjects#85]
I use two GitLab servers; one personal and one for work. I set my GitLab Settings on Webstorm to connect to my work GitLab account, but now I need to switch to my personal account. How can I do that without losing my work settings? I don't want to have to reset the Personal App Token every time I want to switch from server to server.

**Comment by JSosaRDZ** [comment]
I'm reopening the issue because I closed it by mistake. I apologize.

**Comment by jpoa** [comment]
+1

**Comment by PavlikPolivka** [comment]
I found some time and added some basic support for multiple servers.

Now there is a table in settings, fill the form and click the add new button. Fill again.
All server will be used.

Two categories:
Projects with git already (merge request management) will automatically detect what server to use based on remote.

Projects without git (or need of server specification) (share and checkout) will have combo box with list of all servers. 

I have no easy way of testing with multiple server on this PC (no VPN access to my company to try with company gitlab) so I am not 100% sure everything works as expected. Everything worked with one server.

Please report any issues as separate issues. Closing this one.

**Comment by jpoa** [comment]
Thank you!
