### ISSUE TITLE
Cannot Create Merge Request: Can't find GitLab remote

### ISSUE THREAD

**Issue by jona8780** [PavlikPolivka/GitLabProjects#88]
Trying to use Gitlab plugin for PHP storm. When I try and connect to the host url with my token in the github VC settings I get this error: 

Can't login: Can't get user info 404 Not Found

Then if I try and use VCS<Git<Git Labs to create a merge request I get:

Cannot Create Merge Request: Can't find GitLab remote

**Comment by PavlikPolivka** [comment]
Hi.

What version of gitlab are you using? What is the url you have in the server field in settings (replace company name if needed).

**Comment by alirezaGoodarziGmail** [comment]
how to set remote url to gitlab project has already been created in phpstorm?

**Comment by jona8780** [comment]
I am using Version 1.4.10. This is the URL i am using with the company name removed https://gitlab.(company).ca/MCHUGHD/LinksRegistry.git

**Comment by PavlikPolivka** [comment]
@jona8780 it's suppose to be global setting about your gitlab server, not specific for a project, please use https://gitlab.(company).ca/

@alirezaGoodarziGmail not sure what you mean, is it already a git repo? If so when you have the global settings for your Plugin (file, other settings, gitlab projects) it should just detect it automatically. If it's not gitlab repo you can share it to gitlab via VCS menu.

**Comment by jona8780** [comment]
What info should I have entered into the GitHub version Control?

**Comment by PavlikPolivka** [comment]
GitHub version control? This plugin does not do anything with github...
