### ISSUE TITLE
Add GitLab issue tracker integration

### ISSUE THREAD

**Issue by lafafm** [PavlikPolivka/GitLabProjects#89]
Intellij IDE's have a task management functionality

Can GtiLab issues be integrated on it?

Thanks

**Comment by PavlikPolivka** [comment]
Hi.

As far as I know you can just add your gitlab server there.
https://www.jetbrains.com/help/idea/managing-tasks-and-contexts.html

![image](https://user-images.githubusercontent.com/7499182/36865462-e61b0e5e-1d8f-11e8-9c99-7f27d21f987d.png)

Also looks like plugins cannot extend this.
Closing this as this seems to be implemented by JetBrains.
