### ISSUE TITLE
Intellij 2018.1 RC - after selecting GitLab project, IDEA prompts to clone GitHub project

### ISSUE THREAD

**Issue by GJKrupa** [PavlikPolivka/GitLabProjects#94]
Hi,

I've been testing IntelliJ IDEA 2018.1 release candidate and found that when I try to clone a GitLab project using the GitLabProjects plugin, I'm presented with the usual tree of projects but when I select one (cloned via SSH), IDEA then opens the GitHub clone repo window pre-populated with the last repo I cloned from GitHub.com.

I'm running v1.5.3 of the plugin on IDEA 2018.1 RC under Ubuntu 16.04,

Regards,
Gerard Krupa

**Comment by PavlikPolivka** [comment]
Hi,

Thank you for this.
I always called the checkout dialog from GitHub plugin to save me a lot of coding. Seems like they changed some classes so now it's opening it at different point of the flow. 

When I will have some time I will try to fix this (this weekend).
Unfortunately this means that newer versions of plugin will be compatible only with 2018.1 as it's not in my power to maintain bugfixing for multiple versions.

**Comment by PavlikPolivka** [comment]
OK.
So in 2018.1 they pretty much redone how git checkout dialog should work.
Instead there should only only checkout from Git dialog. 
This dialog will load all your repositories from github and other services and will do autocomplete on those.
Plugins can extend that and the git checkout will prompt you what services you have.
This basically means deleting the checkout dialog.

I will do this as this seems more systematic and JetBrains github plugin does it as well.

![image](https://user-images.githubusercontent.com/7499182/37988344-fa006c18-3200-11e8-9daf-d96eea484c4a.png)

**Comment by PavlikPolivka** [comment]
I have implemented the new checkout way. I am not sure if I like it as much as separate dialog but at least it's systematic.
Closing this issue.

**Comment by GJKrupa** [comment]
Thanks very much for the super-quick fix - perfect timing with the 2018.1 release yesterday.
