### ISSUE TITLE
Error 404 when retriving task

### ISSUE THREAD

**Issue by David-C42** [PavlikPolivka/GitLabProjects#96]
Gitlab 10.6.2-ee
PhpStorm 2018.1
GitLab Projects 1.6.0

Opening a new task result a 404 error form GitLab server when retrieving issues list.
"Request failed with HTTP error: 404 Not Found."

Server is correctly configured and the test button result a "Connection is successful".
I can see all the projects.

URL called by Gitlab Projects to Gitlab server :
[30/Mar/2018:09:53:45 +0200] "GET /api/v3/projects/0/issues?page=1&per_page=20&order_by=updated_at&state=opened HTTP/1.1" 404 35 "" "Apache-HttpClient/4.5.2 (Java/1.8.0_152-release)"

It seams that the project ID is not the good one (for thus exemple, it should be 6)

**Comment by PavlikPolivka** [comment]
Hi. I am not really sure where in the plugin I would even call this rest call. There is no support for task management. What exactly are the steps to reproduce this?
