### ISSUE TITLE
Checkout repository from gitlab in menu doesn't exist (phpStorm 2018.1)

### ISSUE THREAD

**Issue by pablo83** [PavlikPolivka/GitLabProjects#97]
Hi, in new phpStorm 2018.1 i don't have possibility to clone repository from giltab.
I have two versions, 2017.3 and 2018.1. In 2017.3 everything look properly, I have option vcs->checkout form version control->gitlab.
In new version this position doesn't exist in menu. I think that's only one bug, rest of plugin functionality seems look good.

**Comment by PavlikPolivka** [comment]
Hi. In 2018.1 there was a change in how git checkout integrations are suppose to work in jetbrains ide. 

If you go to vcs -> checkout -> git it will automatically load all your gitlab and github and any other connected git services into the checkout dialog. 

It's not that nice as separate dialog but it's how this is done in 2018.1....

**Comment by pablo83** [comment]
Thanks! This solution is not intuitive so much...
Your was better :P :)
