### ISSUE TITLE
Plugin Code Review different from GitLab web code review

### ISSUE THREAD

**Issue by uliss3s** [PavlikPolivka/GitLabProjects#98]
The Code Review option on List Merge Requests is showing changes in files that are not in the current Merge Request being analised.

**Comment by PavlikPolivka** [comment]
It uses the actual file on the local copy so it needs both branches localy and up to date. If you are missing some commits localy or did not push some changes to the server the local code review will not be the same as the server one.

This is not perfect but it's using the IDE diff tool, writting my own would be very difficult.

**Comment by uliss3s** [comment]
Oh, i got it. Thanks for answering.
